### ISSUE TITLE
Place cursor inside most inner created elements

### ISSUE THREAD

**Issue by gijsbeijer** [semeniuk/vscode-emmet-live#1]
Hi,

I think it would be great if after the creation of elements the cursor would move into the innermost element(s) instead of selecting the created elements.

Curious about your opinion!

Regards,
Gijs

**Comment by NordicSoft** [comment]
Hi Gijs,

First of all, thank you for your feedback.
You are absolutely right. I planned to implement this but had no time.
But after your request I'll do it for sure! :)

Thanks,
Yurii

**Comment by semeniuk** [comment]
Hi Gijs,

First of all, thank you for your feedback.
You are absolutely right. I planned to implement this but had no time.
But after your request I'll try to do it for sure! :)

Thanks,
Yurii

**Comment by semeniuk** [comment]
Implemented in [v1.0.0](https://github.com/semeniuk/vscode-emmet-live/releases/tag/v1.0.0)

**Comment by gijsbeijer** [comment]
Thanks!
